name: Download new DNS data
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # trigger every day @midnight
    - cron:  '0 0 * * *'
  push:
    branches: [ master, gjm ]
    
  pull_request:
    branches: [ master, gjm ]
    
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Download new DNS data
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download new DNS data
        uses: ./
        with:
            args: python /app/get_dns.py -d historic

      - name: Commit files
        run: |
          find historic -ls
          git config --local user.email "action@github.com"
          git config --local user.name "DNS data download"
          git add historic/*
          git diff-index --quiet HEAD -- || {
              git commit -m "$(date)" -a
              git pull
              repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
              git push
          }
