name: Analyse new DNS data
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Analyse new DNS data
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Analyse new DNS data
        uses: ./
        with:
            commands: "/app/searchfor.sh covid /github/workspace/results /github/workspace/historic"
    
      - name: Commit files
        run: |
          find -ls
          git config --local user.email "action@github.com"
          git config --local user.name "DNS data analyse"
          git add results/*
          git diff-index --quiet HEAD -- || git commit -m "$(date)" -a
          git pull
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
